name: CI

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: install dependencies
        run: npm ci
      - name: print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest