name: release on new release tag

on:
  push:
    tags:
      - v\d+

jobs:
  changelog-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
      - name: install dependencies
        run: npm ci
      - name: run unit tests
        run: npm run test
      - name: install headless playwright
        run: npx playwright install --with-deps chromium
      - name: run e2e tests
        run: npm run e2e-ci
      - name: build application
        run: npm run build
      
      - name: get last correct tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ steps.tagger.outputs.tag }}
          writeToFile: false
      - name: get date and time
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: create an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
          CHANGELOG: ${{ steps.changelog.outputs.changes }}
          DATE: ${{ env.DATE }}
          DEPLOYLINK: ${{ env.DEPLOYLINK }}
      - name: create release branch
        run: |
          git checkout -b release@${{ github.ref_name }}
          git push origin release@${{ github.ref_name }}
      
      - name: deploy on gh-pages
        run: |
          git remote set-url https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
