name: release on new release tag

on:
  push:
    tags:
      - v\d+
  workflow_dispatch:

jobs:
  release-issue:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      issues: write
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
      - name: create an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
          DATE: ${{ github.event.repository.updated_at }}
          CHANGELOG: ${{ steps.build_changelog.outputs.changelog }}
          