name: release on new release tag

on:
  push:
    tags:
      - v\d+
  workflow_dispatch:

jobs:
  release-issue:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      issues: write
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: get last correct tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
      - name: build changelog
        id: build_changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          toTag: ${{ steps.tagger.outputs.tag }}
          fromTag: ${{ github.ref_name }}
      - name: show changelog
        run: echo "${{ toJSON(steps.build_changelog) }}"
      - name: create an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
          DATE: ${{ github.event.repository.updated_at }}
          CHANGELOG: ${{ steps.build_changelog.outputs.changes }}
          