name: release on new release tag

on:
  push:
    tags:
      - v\d+
  workflow_dispatch:

jobs:
  changelog-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: get last correct tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ steps.tagger.outputs.tag }}
          writeToFile: false
      - name: create an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
          DATE: ${{ github.event.repository.updated_at }}
          CHANGELOG: ${{ steps.changelog.outputs.changes }}
  release-branch:
    needs: changelog-release
    runs-on: ubuntu-22.04
    permissions:
      deployments: write
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Create Branch
      id: create_branch
      uses: lablnet/create-branch-from-tag@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
