name: release on new release tag

on:
  push:
    tags:
      - v\d+
  workflow_dispatch:

jobs:
  release-issue:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: get last correct tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          fromTag: ${{ steps.tagger.outputs.tag }}
          toTag: ${{ github.ref_name }}
      - name: show changelog
        run: echo "${{ toJSON(steps.build_changelog) }}"
      # - name: create an issue
      #   uses: JasonEtco/create-an-issue@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     RELEASE_VERSION: ${{ github.ref_name }}
      #     DATE: ${{ github.event.repository.updated_at }}
      #     CHANGELOG: ${{ toJSON(github.event.commits) }}
          