name: release on new release tag

on:
  push:
    tags:
      - v\d+
  workflow_dispatch:

jobs:
  release-issue:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      issues: write
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: get last correct tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
      - name: Find all issues
        id: issues
        uses: lee-dohm/select-matching-issues@v1
        with:
          query: 'label:release'
          token: ${{ github.token }}
          format: list
      - name: show found issues
        run: echo "${{ toJSON(steps.issues.outputs) }}"
      # - name: create an issue
      #   uses: JasonEtco/create-an-issue@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     RELEASE_VERSION: ${{ github.ref_name }}
      #     DATE: ${{ github.event.repository.updated_at }}
      #     CHANGELOG: ${{ toJSON(github.event.commits) }}
          