name: run autotests on PR

on: pull_request

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
      - name: install dependencies
        run: npm ci
      - name: print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: run unit tests
        run: npm run test
        
jobs:
  e2e-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
      - name: install dependencies
        run: npm ci
      - name: print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: install headless playwright
        run: npx playwright install --with-deps chromium
      - name: run e2e tests
        run: npm run e2e-ci